# Gitleaks configuration for API key detection
title = "Gitleaks config for Voypath"

[[rules]]
id = "google-api-key"
description = "Google API Key"
regex = '''AIza[0-9A-Za-z\-_]{35}'''
tags = ["key", "Google", "security"]

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api_key|apikey|api-key)\s*[:=]\s*['"][0-9a-zA-Z\-_]{20,}['"]'''
tags = ["key", "API", "generic"]

[[rules]]
id = "firebase-api-key"
description = "Firebase API Key"
regex = '''(?i)(firebase_api_key|FIREBASE_API_KEY)\s*[:=]\s*['"][0-9a-zA-Z\-_]{35,}['"]'''
tags = ["key", "Firebase"]

[[rules]]
id = "supabase-anon-key"
description = "Supabase Anon Key"
regex = '''eyJ[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*'''
tags = ["key", "Supabase", "JWT"]

[[rules]]
id = "stripe-secret-key"
description = "Stripe Secret Key"
regex = '''sk_(test|live)_[0-9a-zA-Z]{24,}'''
tags = ["key", "Stripe", "payment"]

[[rules]]
id = "openai-api-key"
description = "OpenAI API Key"
regex = '''sk-[A-Za-z0-9]{48}'''
tags = ["key", "OpenAI"]

[allowlist]
description = "Allowlisted files and paths"
files = [
    ".gitleaks.toml",
    "README.md",
    "package-lock.json",
    "yarn.lock"
]
paths = [
    "node_modules",
    ".git",
    "dist",
    "build"
]